---
- name: Create Nutanix Project
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: "{{ nutanix_host }}"
      nutanix_username: "{{ nutanix_username }}"
      nutanix_password: "{{ nutanix_password }}"
      validate_certs: false
  tasks:
    - name: Create a project
      nutanix.ncp.ntnx_projects:
        name: "{{ project_name }}"
        desc: "{{ project_description }}"
        subnets:
          - name: "{{ subnet_name }}"
        default_subnet:
          name: "{{ subnet_name }}"
        resource_limits:
          - resource_type: STORAGE
            limit: "{{ storage_limit }}"
          - resource_type: MEMORY
            limit: "{{ memory_limit }}"
          - resource_type: VCPUS
            limit: "{{ vcpus_limit }}"
        accounts:
          - name: "{{ account_name }}"
        collaboration: true
        role_mappings:
          - user:
              principal_name: "user3@ntnx.local"
              directory_service_uuid: "{{ directory_service_uuid }}"
            role:
              name: "Project Admin"
      register: project_creation_result

    - name: Debug project creation result
      debug:
        var: project_creation_result
